name: PlatformIO CI Workflow

run-name: ${{ github.actor }} pushed new update

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.List_os }}
    strategy:
      matrix:
        List_os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
                ~/.cache/pip
                ~/.platformio/.cache
            key: ${{ runner.os }}-pio
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Install PlatformIO Core
          run: pip install --upgrade platformio
        - name: Build PlatformIO Project
          run: pio run

